### ISSUE TITLE
"ValueError: math domain error" when training on a large file

### ISSUE THREAD

**Issue by TianboJi** [wang-h/FMDL#1]
I have a large training file with 1252976 lines. When I use it to train a model(vocab_size: 30000), it raised an error like following:
```
Building pair statistics: 2116233it [00:03, 614115.37it/s]
Commit to codebook:   8% 688/8761 [00:00<00:10, 753.77it/s]
Traceback (most recent call last):
  File "learn_mdl.py", line 202, in <module>
    main(args)
  File "learn_mdl.py", line 161, in main
    codebook = trainer(args.iterations, args.verbose)
  File "learn_mdl.py", line 150, in train
    if not self.update_codebook(candidates):
  File "learn_mdl.py", line 129, in update_codebook
    if self.commit_and_success(pair, total, cost):
  File "learn_mdl.py", line 106, in commit_and_success
    if sum(self.compute_cost(w1, w2, total)) > 0:
  File "learn_mdl.py", line 63, in compute_cost
    float(total), float(c1), float(c2), self.data_len)
  File "learn_mdl.py", line 68, in compute_data_cost
    data_cost += c1 * math.log(c1 / n)
ValueError: math domain error
```
How can I fix it? Thanks in advance

**Comment by wang-h** [comment]
Have you removed all white spaces?

I did not write this code carefully, but I think the problem is a common python problem, which indicates that ‘c1’ or ‘n’ is zero.

It often happens when your input text contains white spaces, I guess.

Please check the input file to make sure no white spaces in the raw text. 

BTW,
I would be very appreciate it If you can send more error details to me. For example, you can print the word pair (w1,w2 ).

Have you tried other text files?

Best.

**Comment by TianboJi** [comment]
Hi, after searching in vim editor, I think there is no white space in it. 
If I understand you correctly, I guess the word pairs you mentioned above are two parameters `w1`, `w2` which are passed to function `compute_cost`. So I just directly printed them out during training, the latest ones before error raised are:
```
('长',) ('官',)
('世',) ('贸',)
('广',) ('播',)
('文',) ('件',)
('宗',) ('教',)
('/',) ('w',)
```
I trained some other files, some worked but some did not.  Here are part of their word pairs:

```
('互',) ('利',)
('太',) ('平',)
('确',) ('定',)
('阴',) ('谋',)
('电',) ('视',)
('制',) ('定',)
('显',) ('然',)
('4',) ('0',)
```
```
('详',) ('情',)
('支',) ('援',)
('驾',) ('驶',)
('用',) ('途',)
('专',) ('业',)
('t',) ('t',)
('/',) ('w',)
```

**Comment by wang-h** [comment]
Thanks for your feedback. 
One more thing needs to confirm: which OS is using? Window or Linux?
Have you tried removing all '/' from your training set or substituting them with '$w'?
However, no error detected in my testing (Ubuntu).

P.s,  I modify the code and naïvely solve this bug by raising an exception.
It should work now.

**Comment by TianboJi** [comment]
Great! Now it works! 
My OS is macOS 10.13.5 and we are configuring our Ubuntu Server since its current cmake version is not compatible. BTW, the code runs perfectly without removing '/' (usually it comes from a http link). I think it is able to deal with special characters as long as there is no space in it.
Thanks for the update!
